apiVersion: v1
kind: PersistentVolume
metadata:
  name: laravel-pv
  namespace: laravel-app
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/laravel"
