apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: laravel-app
data:
  nginx.conf: |
    server {
        listen 80;
        server_name example.local;

        root /var/www/public;
        index index.php index.html;

        # Handle static files and routes
        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        # Forward API requests to Laravel service
        location /app {
            proxy_pass laravel:9000;  # ✅ Fixed
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Forward PHP files to PHP-FPM
        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass laravel:9000;  # ✅ No http:// needed here
            fastcgi_param SCRIPT_FILENAME /var/www/public$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT /var/www/public;
            fastcgi_param SERVER_NAME $host;
            fastcgi_param SERVER_PORT $server_port;
            fastcgi_param SERVER_ADDR $server_addr;
        }

        # Deny access to .htaccess files
        location ~ /\.ht {
            deny all;
        }
    }
